DELETE http://localhost:3001/api/blogs/651ec48e19a7e36f089ebb31 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXgiLCJpZCI6IjY1MWIwNmYwYTY0N2Y2MDc0NjM0NWU0ZCIsImlhdCI6MTY5NjUxNTEzMSwiZXhwIjoxNjk2NTE4NzMxfQ.Ql205qylspTDheZzxjEBe6oLO2juZyjYHyu-U12LU4w