POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json

    {
        "title": "Note 8",
        "author": "Alex",
        "url": "http://...com",
        "likes": 12,
        "user": "651989ab4ba56b4a3b8c794b"
    }
###
POST http://localhost:3001/api/users/ HTTP/1.1
Content-Type: application/json

    {
      "username": "v",
      "name": "Valid User",
      "password": ""
    }